weights: ./models/*your_trained_weights*

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/Kinetics/Cooking_Activity/test_data.npy
  label_path: ./data/Kinetics/Cooking_Activity/test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 66
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 1
